FROM rust:latest AS builder

RUN curl -L https://sp1up.succinct.xyz | bash
RUN /root/.sp1/bin/sp1up 

WORKDIR /app
COPY .cargo .cargo
COPY ./contracts/ ./contracts
COPY ./server ./server
COPY ./elf ./elf
COPY Cargo.toml . 
COPY Cargo.lock .

RUN cargo build --bin server

# RUNNER
FROM rust:latest

WORKDIR /app

COPY --from=builder /app/target/debug/server ./

EXPOSE 4000

CMD ["./server"]


